"""empty message

Revision ID: beb7672a6edf
Revises: 
Create Date: 2023-07-06 14:36:02.486891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb7672a6edf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('emblem', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions')),
    sa.UniqueConstraint('name', name=op.f('uq_competitions_name'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shortName', sa.String(), nullable=True),
    sa.Column('crestImg', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('clubColors', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('competitionTeams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('competitionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competitionId'], ['competitions.id'], name=op.f('fk_competitionTeams_competitionId_competitions')),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], name=op.f('fk_competitionTeams_teamId_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitionTeams'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchDay', sa.Integer(), nullable=True),
    sa.Column('homeTeamID', sa.Integer(), nullable=True),
    sa.Column('awayTeamID', sa.Integer(), nullable=True),
    sa.Column('areaId', sa.Integer(), nullable=True),
    sa.Column('areaName', sa.String(), nullable=True),
    sa.Column('utcDate', sa.DateTime(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['awayTeamID'], ['teams.id'], name=op.f('fk_matches_awayTeamID_teams')),
    sa.ForeignKeyConstraint(['homeTeamID'], ['teams.id'], name=op.f('fk_matches_homeTeamID_teams')),
    sa.ForeignKeyConstraint(['winner'], ['teams.id'], name=op.f('fk_matches_winner_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('favTeam', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favTeam'], ['teams.id'], name=op.f('fk_users_favTeam_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('savedMatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('matchId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matchId'], ['matches.id'], name=op.f('fk_savedMatches_matchId_matches')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('fk_savedMatches_userId_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_savedMatches'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savedMatches')
    op.drop_table('users')
    op.drop_table('matches')
    op.drop_table('competitionTeams')
    op.drop_table('teams')
    op.drop_table('competitions')
    # ### end Alembic commands ###
